<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Emergence.Foundation/Emergence.Foundation.csproj" />
    <ProjectReference Include="../Emergence.Persistence/Emergence.Persistence.csproj" />
  </ItemGroup>
</Project>
