<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Emergence.Foundation/Emergence.Foundation.csproj" />
    <ProjectReference Include="../Emergence.Model/Emergence.Model.csproj" />
    <ProjectReference Include="../Emergence.Simulation/Emergence.Simulation.csproj" />
    <ProjectReference Include="../Emergence.Persistence/Emergence.Persistence.csproj" />
    <ProjectReference Include="../Emergence.Presentation.Contracts/Emergence.Presentation.Contracts.csproj" />
  </ItemGroup>
</Project>
