<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Emergence.Foundation/Emergence.Foundation.csproj" />
    <ProjectReference Include="../Emergence.Model/Emergence.Model.csproj" />
    <ProjectReference Include="../Emergence.Presentation.Contracts/Emergence.Presentation.Contracts.csproj" />
  </ItemGroup>
</Project>
